name: Daily Check-in2

on:
  schedule:
    # 北京时间 01:00 (即 UTC 时间前一天 17:00)
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    # ------------------ 新增：随机延迟步骤 ------------------
    - name: Delay randomly
      # 如果是手动触发 (workflow_dispatch)，不等待直接执行；如果是定时任务，则随机等待 1~1800 秒（30分钟内）
      if: github.event_name == 'schedule'
      run: |
        DELAY=$((RANDOM % 7200 + 1))
        echo "⏰ 为模拟真实行为，随机等待 $DELAY 秒后开始签到..."
        sleep $DELAY
    # --------------------------------------------------------
    
    - name: Run check-in script
      run: python ./main.py
      env:
        TZ: 'Asia/Shanghai'
        IKUUU_COOKIE_1: ${{ secrets.IKUUU_COOKIE_1 }}
        IKUUU_COOKIE_2: ${{ secrets.IKUUU_COOKIE_2 }}
    
    - name: Commit results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add checkin_result.txt
        git commit -m "Update checkin detailed logs" || exit 0
        git push
